import { SYSTEM, tokens } from './core.js';

export function providersFromEnv(env = process.env) {
  const price = key => env[key] === undefined ? null : Number(env[key]);
  return [
    { id: 'demo', name: 'Demo · offline', model: 'deterministic-demo', configured: true, maxContext: 64000, inputPrice: 0, outputPrice: 0 },
    { id: 'anthropic', name: 'Anthropic', model: env.ANTHROPIC_MODEL || '', configured: Boolean(env.ANTHROPIC_API_KEY && env.ANTHROPIC_MODEL), maxContext: Number(env.ANTHROPIC_CONTEXT || 32000), inputPrice: price('ANTHROPIC_INPUT_PRICE'), outputPrice: price('ANTHROPIC_OUTPUT_PRICE'), key: env.ANTHROPIC_API_KEY },
    { id: 'ollama', name: 'Ollama · local', model: env.OLLAMA_MODEL || '', configured: Boolean(env.OLLAMA_MODEL), maxContext: Number(env.OLLAMA_CONTEXT || 16000), inputPrice: 0, outputPrice: 0, baseUrl: env.OLLAMA_URL || 'http://127.0.0.1:11434' }
  ];
}
export function publicProviders(providers) { return providers.map(({ key, baseUrl, ...publicFields }) => publicFields); }
export async function generate(provider, context, fetcher = fetch) {
  const prompt = JSON.stringify(context.packet);
  if (provider.id === 'demo') {
    const text = JSON.stringify({
      message: `Offline demo: compiled ${context.packet.files.length} relevant files into a portable handoff. I prepared a workspace note for review. Select a configured provider for real coding assistance.`,
      summary: `Demo task: ${context.packet.request.slice(0, 1000)}. A workspace note was proposed; acceptance and verification are still pending.`,
      changes: [{ path: 'cascade-note.md', content: `# Workspace handoff\n\nTask: ${context.packet.request}\n\n## Decisions\n${context.packet.decisions.map(d => '- ' + d).join('\n') || '- No decisions recorded.'}\n\n## Relevant files\n${context.packet.files.map(f => '- ' + f.path).join('\n')}\n\nGenerated by the offline demo. No model was called.\n`, reason: 'Demonstrate a reviewable change and persistent handoff.' }]
    });
    return { text, inputTokens: context.inputTokens, outputTokens: tokens(text), estimated: true };
  }
  let url, body, headers = { 'Content-Type': 'application/json' };
  if (provider.id === 'anthropic') {
    url = 'https://api.anthropic.com/v1/messages';
    headers = { ...headers, 'x-api-key': provider.key, 'anthropic-version': '2023-06-01' };
    body = { model: provider.model, max_tokens: 4096, system: SYSTEM, messages: [{ role: 'user', content: prompt }] };
  } else if (provider.id === 'ollama') {
    url = provider.baseUrl.replace(/\/$/, '') + '/api/chat';
    body = { model: provider.model, stream: false, format: 'json', messages: [{ role: 'system', content: SYSTEM }, { role: 'user', content: prompt }], options: { num_ctx: provider.maxContext, num_predict: 4096 } };
  } else throw new Error('Unknown provider');
  let response;
  try {
    response = await fetcher(url, { method: 'POST', headers, body: JSON.stringify(body), signal: AbortSignal.timeout(120000) });
  } catch {
    const error = new Error(provider.name + ' connection failed or timed out');
    error.retryable = true;
    throw error;
  }
  if (!response.ok) {
    const error = new Error(`${provider.name} returned HTTP ${response.status}`);
    error.retryable = [429, 500, 502, 503, 504, 529].includes(response.status);
    throw error;
  }
  const data = await response.json();
  const text = provider.id === 'anthropic' ? (data.content || []).filter(b => b.type === 'text').map(b => b.text).join('\n') : data.message?.content;
  if (typeof text !== 'string') throw new Error('Provider returned no text');
  const input = provider.id === 'anthropic' ? data.usage?.input_tokens : data.prompt_eval_count;
  const output = provider.id === 'anthropic' ? data.usage?.output_tokens : data.eval_count;
  return { text, inputTokens: input ?? context.inputTokens, outputTokens: output ?? tokens(text), estimated: input == null || output == null };
}
export async function route({ providers, selected, mode, compile, onAttempt = () => {}, generateFn = generate }) {
  const primary = providers.find(p => p.id === selected && p.configured);
  if (!primary) throw new Error('Configure the selected provider on the server first');
  if (!['manual', 'automatic'].includes(mode)) throw new Error('Unknown routing mode');
  const candidates = [primary, ...(mode === 'automatic' && selected !== 'demo' ? providers.filter(p => p.configured && p.id !== selected && p.id !== 'demo') : [])];
  const attempts = [];
  for (const provider of candidates) {
    try {
      if (!Number.isFinite(provider.maxContext) || provider.maxContext < 6096) throw new Error('Provider context window must be at least 6,096 tokens');
      const context = compile(provider.maxContext - 4096);
      const result = await generateFn(provider, context);
      attempts.push({ provider: provider.id, status: 'completed' });
      return { provider, context, result, attempts };
    } catch (error) {
      attempts.push({ provider: provider.id, status: 'failed', error: error.message });
      onAttempt(provider.id, error.message);
      if (!error.retryable) throw error;
    }
  }
  throw new Error(`All eligible providers failed: ${attempts.map(a => a.error).join('; ')}`);
}
